[package]
edition = "2021"
license = "private"
name = "bitoids"
resolver = "2"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.dev]
opt-level = 1
split-debuginfo = "unpacked"

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
incremental = true
lto = "fat"
opt-level = "z"
strip = "debuginfo"

[features]
inspector = ["dep:bevy-inspector-egui"]

[dependencies]
bevy = {version = "0.19.0", default-features = false, features = [
  "default_app",
  "2d_bevy_render",
  "ui_bevy_render",
  "bevy_winit",
  "default_font",
  "std",
  "multi_threaded",
  "x11",
  "wayland",
  "web",
  "serialize",
  "trace",
  "png",
  "webgl2"
]}
bevy-inspector-egui = {version = "0.37.0", optional = true}
colored = {version = "3.1", optional = true}
console_error_panic_hook = "0.1.7"
getrandom = {version = "0.4", features = ["wasm_js"]}
rand = "0.10.2"
wasm-bindgen = {version = "0.2", default-features = false}
wasm-bindgen-futures = "0.4"
